2769 - Create change preferred language page
DTS-STN/canadian-dental-care-plan pull request #136
Opened 2024-01-23 18:22 UTC by shawn320

- Create route for preferred language edit page [2812](https://dev.azure.com/DTS-STN/Canada%20Dental%20Care%20Plan/_sprints/taskboard/LiteBrite/Canada%20Dental%20Care%20Plan/Sprint%201?workitem=2812)
- Create loader [2819](https://dev.azure.com/DTS-STN/Canada%20Dental%20Care%20Plan/_sprints/taskboard/LiteBrite/Canada%20Dental%20Care%20Plan/Sprint%201?workitem=2819)
- Create action [2820](https://dev.azure.com/DTS-STN/Canada%20Dental%20Care%20Plan/_sprints/taskboard/LiteBrite/Canada%20Dental%20Care%20Plan/Sprint%201?workitem=2820)
- Create handle [2821](https://dev.azure.com/DTS-STN/Canada%20Dental%20Care%20Plan/_sprints/taskboard/LiteBrite/Canada%20Dental%20Care%20Plan/Sprint%201?workitem=2821)

2024-01-23 18:32 UTC, gregory-j-baker commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +  };
I also don't think the event handler is necessary.. Unless I'm missing something.

2024-01-23 18:32 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +  const [selectedLanguage, setSelectedLanguage] = useState(userInfo.preferredLanguage || '')
I don't think useState is required if we are using default browser behavior as Remix suggest. Default checked radio should come from loader and/or action.

https://www.w3schools.com/tags/att_input_type_radio.asp

2024-01-23 18:32 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +        <fieldset className="gc-chckbxrdio">
A legend is missing if I look at GCWeb standards. 
https://wet-boew.github.io/GCWeb/components/gc-chckbxrdio/gc-chckbxrdio-en.html#:~:text=with%20explicit%20labels-,Which%20is%20your%20favorite%20pet%3F,-Dog

2024-01-23 18:38 UTC, Fbasham commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +  };
Correct. We can get away from using controlled components in this case.  Use `defaultChecked={userInfo.preferredLanguage === 'en'} ` for example.

2024-01-23 20:12 UTC, sebastien-comeau requested changes
Trivial changes

2024-01-23 20:12 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +                id="en"
Use relevant `id` for the `radio` to help with unit test.
```suggestion
                id="preferred-language-option-en"
```

2024-01-23 20:12 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +                id="fr"
Use relevant `id` for the `radio` to help with unit test.

```suggestion
                id="preferred-language-option-fr"
```

2024-01-24 01:59 UTC, gregory-j-baker approved these changes

2024-01-24 10:31 UTC, gregory-j-baker requested changes

2024-01-24 10:31 UTC, gregory-j-baker commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +  console.log(userInfo.preferredLanguage)
This should be removed.

2024-01-24 10:31 UTC, gregory-j-baker commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.edit.tsx
> +const i18nNamespaces = getTypedI18nNamespaces('gcweb', 'personal-information');
Since `gcweb` isn't being used anywhere in the page, it should be removed.

2024-01-24 14:27 UTC, sebastien-comeau approved these changes

2024-01-24 14:38 UTC, merged