public check status landing page
DTS-STN/canadian-dental-care-plan pull request #1366
Opened 2024-05-13 19:06 UTC by nibivi77

### Description
First page of the public check-status
AB#3544

[Figma Link](https://www.figma.com/design/6mD8mKepCJFBZmTbu40VMy/CDCP-Online-Status-Checker?node-id=3139-3993&t=1BPgfyJ2xdlAP50I-0)

### Checklist

- [x] I have tested the changes locally
- [x] I have updated the documentation if necessary
- [ ] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

### Test Instructions
Navigate to /status to see the changes.

### Additional Notes
I left some translations that are not used since they will be used in the next page. (Next PR)

2024-05-15 09:47 UTC, gregory-j-baker requested changes

2024-05-15 09:47 UTC, gregory-j-baker commented on frontend/public/locales/fr/status.json
> +    "thank-you": "Merci d'utiliser le vérificateur de l'état d'une demande du Régime canadien de soins dentaires. Nous avons établi conditions d'utilisation de ce service (<<conditions d'utilisation>
```suggestion
    "thank-you": "Merci d'utiliser le vérificateur de l'état d'une demande du Régime canadien de soins dentaires. Nous avons établi conditions d'utilisation de ce service («\u00a0conditions d'utilisation\u00a0»). Veuillez les lire attentivement.",
```

2024-05-21 13:39 UTC, gregory-j-baker approved these changes

2024-05-21 15:34 UTC, nicholas-ly commented on frontend/public/locales/en/status.json
> +      "self-agreement": "Using the Status Checker means that you have read and agree to these Terms of Use and the Privacy Notice Statement.If, at any time, you withdraw your agreement to any of the
```suggestion
      "self-agreement": "Using the Status Checker means that you have read and agree to these Terms of Use and the Privacy Notice Statement. If, at any time, you withdraw your agreement to any of the Terms you must stop use of the Online Status Checker.",
```

2024-05-21 18:15 UTC, nicholas-ly approved these changes

2024-05-21 18:15 UTC, merged