3599 New screen for when a child's age is over 18
DTS-STN/canadian-dental-care-plan pull request #1384
Opened 2024-05-15 17:29 UTC by Fbasham

### Description
Add screen B.10.

Note: the logic for this screen hasn't been implemented.  This PR just addresses the scaffolding.

### Related Azure Boards Work Items
AB#3599

### Checklist

- [ ] I have tested the changes locally
- [ ] I have updated the documentation if necessary
- [ ] I have added/updated tests that prove my fix is effective or that my feature works
- [ ] I have checked that my code follows the project's coding style by running `npm run format:check`
- [ ] I have checked that my code contains no linting errors by running `npm run lint`
- [ ] I have checked that my code contains no type errors by running `npm run typecheck`
- [ ] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [ ] I have checked that all e2e tests pass by running `npm run test:e2e`

2024-05-16 15:05 UTC, sebastien-comeau requested changes

2024-05-16 15:05 UTC, sebastien-comeau commented on frontend/public/locales/en/apply-adult-child.json
French locale has not been updated.

2024-05-17 11:30 UTC, Fbasham commented on frontend/public/locales/en/apply-adult-child.json
it's done, boss

2024-05-17 12:56 UTC, sebastien-comeau approved these changes

2024-05-17 13:03 UTC, merged