AB#3600 -- Updated routes for adult-child apply-yourself page
DTS-STN/canadian-dental-care-plan pull request #1386
Opened 2024-05-15 18:06 UTC by AdamP-HRSDC-RHDCC

### Description
Updated routes for adult-child apply-yourself page (Issue with /adult-child/apply-yourself  - Redirect to proper screen)

### Related Azure Boards Work Items
AB#3600

### Screenshots (if applicable)
n/a

### Checklist
- [x] I have tested the changes locally
- [x] I have updated the documentation if necessary
- [ ] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

### Test Instructions
Confirm figma flow on DTC page with all children over/under 18 options selected.

### Additional Notes
n/a

2024-05-16 16:39 UTC, sebastien-comeau requested changes

2024-05-16 16:39 UTC, sebastien-comeau commented on frontend/app/routes/$lang+/_public+/apply+/$id+/adult-child/apply-yourself.tsx
> +  }
```suggestion
  invariant(state.dateOfBirth, 'Expected state.dateOfBirth to be defined');
```

2024-05-16 17:07 UTC, sebastien-comeau submitted a review, later dismissed

2024-05-17 12:56 UTC, sebastien-comeau requested changes

2024-05-17 12:56 UTC, sebastien-comeau commented on frontend/app/routes/$lang+/_public+/apply+/$id+/adult-child/disability-tax-credit.tsx
> +  return redirect(getPathById('$lang+/_public+/apply+/$id+/adult-child/parent-or-guardian', params));
Change the conditions.

```
IF "NO" THEN redirect "adult-child/parent-or-guardian" END

// at this point it's "YES"

IF NOT "allChildrenUnder18" THEN redirect "adult-child/apply-yourself" END

redirect "adult-child/applicant-information"
```

2024-05-17 15:43 UTC, AdamP-HRSDC-RHDCC commented on frontend/app/routes/$lang+/_public+/apply+/$id+/adult-child/apply-yourself.tsx
> +    return redirect(getPathById('$lang+/_public+/apply+/$id+/adult-child/living-independently', params));
Changed "youth" to redirect to adult flow

2024-05-17 15:43 UTC, AdamP-HRSDC-RHDCC commented on frontend/app/routes/$lang+/_public+/apply+/$id+/adult-child/disability-tax-credit.tsx
> +  return redirect(getPathById('$lang+/_public+/apply+/$id+/adult-child/parent-or-guardian', params));
Updated conditionals

2024-05-17 15:45 UTC, sebastien-comeau approved these changes

2024-05-17 15:47 UTC, merged