AB#2826: integrate lookup service to personal index and confirm preference language pages
DTS-STN/canadian-dental-care-plan pull request #222
Opened 2024-01-30 17:29 UTC by carolinegeorge-gov

[AB#2826](https://dev.azure.com/DTS-STN/1fc40a8f-28cf-47bc-b6e4-1c234bd06177/_workitems/edit/2826): 
* integrated `lookup-service` `getPreferenceLanguage` to `personal-info-index` and `preference-language-confirm`  pages
* removed unused locale files

2024-01-30 17:32 UTC, gregory-j-baker commented
@carolinegeorge-gov looks like your commits aren't signed correctly.

2024-01-30 18:02 UTC, sebastien-comeau requested changes

2024-01-30 18:02 UTC, sebastien-comeau commented on frontend/app/utils/locale-utils.ts
> +export function getNameByLanguage(language: string, languageTranslation: { nameEn?: string; nameFr?: string } | null) {
`| null` remove the null type. Null check should be made at when calling `getNameByLanguage`.

2024-01-31 13:52 UTC, sebastien-comeau requested changes

2024-01-31 13:52 UTC, sebastien-comeau commented on frontend/.env copy.example
The file must be removed.

2024-01-31 13:52 UTC, sebastien-comeau commented on frontend/__tests__/routes/_gcweb-app.personal-information.preferred-language.confirm.test.tsx
@gregory-j-baker might have an idea on how to mock RAOIDC.

2024-01-31 13:52 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information._index.tsx
> +  const preferredLanguage = userInfo.preferredLanguage ? await lookupService.getPreferredLanguage(userInfo?.preferredLanguage) : null;
```suggestion
  const preferredLanguage = userInfo.preferredLanguage ? await lookupService.getPreferredLanguage(userInfo.preferredLanguage) : undefined;
```

2024-01-31 13:52 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information._index.tsx
> +          {getNameByLanguage(i18n.language, preferredLanguage)}
Use [Logical AND operator (&&)](https://react.dev/learn/conditional-rendering#logical-and-operator-)
```suggestion
          {preferredLanguage && getNameByLanguage(i18n.language, preferredLanguage)}
```

2024-01-31 13:52 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.confirm.tsx
> +  return json({ userInfo, preferredLanguage: await lookupService.getPreferredLanguage(await session.get('preferredLanguage')) });
```suggestion
  const sessionPreferredLanguage = await session.get('preferredLanguage');
  const preferredLanguage = await lookupService.getPreferredLanguage(sessionPreferredLanguage);
  return json({ userInfo, preferredLanguage });
```

2024-01-31 13:52 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.confirm.tsx
> +          <dd> {getNameByLanguage(i18n.language, preferredLanguage)}</dd>
Use [Logical AND operator (&&)](https://react.dev/learn/conditional-rendering#logical-and-operator-)
```suggestion
          <dd>{preferredLanguage && getNameByLanguage(i18n.language, preferredLanguage)}</dd>
```

2024-01-31 17:56 UTC, sebastien-comeau commented on frontend/app/utils/locale-utils.ts
> +export function getNameByLanguage(language: string, languageTranslation: { nameEn?: string; nameFr?: string } | null) {
Fixed it to be able to close the user story.

2024-01-31 17:57 UTC, sebastien-comeau commented on frontend/.env copy.example
Fixed it to be able to close the user story.

2024-01-31 17:57 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information._index.tsx
> +          {getNameByLanguage(i18n.language, preferredLanguage)}
Fixed it to be able to close the user story.

2024-01-31 17:57 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information._index.tsx
> +  const preferredLanguage = userInfo.preferredLanguage ? await lookupService.getPreferredLanguage(userInfo?.preferredLanguage) : null;
Fixed it to be able to close the user story.

2024-01-31 17:57 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.confirm.tsx
> +  return json({ userInfo, preferredLanguage: await lookupService.getPreferredLanguage(await session.get('preferredLanguage')) });
Fixed it to be able to close the user story.

2024-01-31 17:57 UTC, sebastien-comeau commented on frontend/app/routes/_gcweb-app.personal-information.preferred-language.confirm.tsx
> +          <dd> {getNameByLanguage(i18n.language, preferredLanguage)}</dd>
Fixed it to be able to close the user story.

2024-01-31 17:58 UTC, sebastien-comeau submitted a review, later dismissed

2024-01-31 18:00 UTC, nicholas-ly commented
My bad... I merged https://github.com/DTS-STN/canadian-dental-care-plan/pull/233 without knowing this PR fixes it.

2024-01-31 18:02 UTC, Fbasham commented
> My bad... I merged #233 without knowing this PR fixes it.

my bad too for not checking this PR

2024-01-31 18:03 UTC, sebastien-comeau approved these changes

2024-01-31 18:05 UTC, merged