AB#2857 new home address validation
DTS-STN/canadian-dental-care-plan pull request #251
Opened 2024-02-02 18:24 UTC by leiye29

### Description

1. add validation into home-address/edit
2. map address api to application address when get address from api
3. map application address to address api when try to save address

### Related Azure Boards Work Items

### Screenshots (if applicable)

### Checklist

- [v] I have tested the changes locally
- [ ] I have updated the documentation if necessary
- [ ] I have added tests that prove my fix is effective or that my feature works
- [v] I have checked that my code follows the project's coding style by running `npm run format:check`
- [v] I have checked that my code contains no linting errors by running `npm run lint`
- [v] I have checked that my code contains no type errors by running `npm run typecheck`
- [v] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [v] I have checked that all e2e tests pass by running `npm run test:e2e -- run`

### Test Instructions

### Additional Notes

2024-02-02 18:35 UTC, sebastien-comeau requested changes

2024-02-02 19:37 UTC, leiye29 commented on frontend/app/routes/_gcweb-app.personal-information.home-address.edit.tsx
> +    };
fixed

2024-02-02 19:54 UTC, nicholas-ly submitted a review, later dismissed

2024-02-02 20:09 UTC, leiye29 commented on frontend/app/routes/_gcweb-app.personal-information.home-address.edit.tsx
> +    form: getErrorMessage(actionData?.errors.formErrors?.[0]),
removed.

2024-02-05 13:27 UTC, nicholas-ly submitted a review, later dismissed

2024-02-05 14:27 UTC, leiye29 commented on frontend/app/routes/_gcweb-app.personal-information.home-address.confirm.tsx
> +              <p className="m-0">{homeAddressInfo?.postalCode}</p>
updated

2024-02-05 14:27 UTC, leiye29 commented on frontend/app/routes/_gcweb-app.personal-information.home-address.confirm.tsx
> +              <p className="m-0">{newHomeAddress.postalCode}</p>
updated

2024-02-05 14:57 UTC, nicholas-ly commented on frontend/app/routes/_gcweb-app.personal-information.home-address.confirm.tsx
> +              <p className="m-0">{newHomeAddress.postalCode}</p>
Resolving as `Address` component is now used.

2024-02-05 14:57 UTC, nicholas-ly commented on frontend/app/routes/_gcweb-app.personal-information.home-address.confirm.tsx
> +              <p className="m-0">{homeAddressInfo?.postalCode}</p>
Resolving as `Address` component is now used.

2024-02-05 14:58 UTC, nicholas-ly approved these changes

2024-02-05 16:34 UTC, merged