2999 - Access to dental insurance question route (front end)
DTS-STN/canadian-dental-care-plan pull request #550
Opened 2024-02-29 19:22 UTC by shawn320

### Description
Added a new route under intake/id for `Access to dental insurance` question. This pr is for the frontend UI, I will create the api in a separate pr.

### Related Azure Boards Work Items
https://dev.azure.com/DTS-STN/Canada%20Dental%20Care%20Plan/_boards/board/t/Kanban/Stories

### Screenshots (if applicable)

### Checklist

- [ ] I have tested the changes locally
- [ ] I have updated the documentation if necessary
- [ ] I have added/updated tests that prove my fix is effective or that my feature works
- [ ] I have checked that my code follows the project's coding style by running `npm run format:check`
- [ ] I have checked that my code contains no linting errors by running `npm run lint`
- [ ] I have checked that my code contains no type errors by running `npm run typecheck`
- [ ] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [ ] I have checked that all e2e tests pass by running `npm run test:e2e`

### Test Instructions

### Additional Notes

2024-02-29 19:42 UTC, sebastien-comeau requested changes

2024-02-29 19:42 UTC, sebastien-comeau commented on frontend/app/components/input-radios.tsx
> +  children?: ReactNode;
Remove this new prop and use `helpMessagePrimary`. You can use `helpMessagePrimaryClassName` to override the default styling.

2024-02-29 19:42 UTC, sebastien-comeau commented on frontend/app/routes/_public+/intake+/$id+/dental-insurance.tsx
> +              <ul className="mb-4 list-disc pl-4">
Use `helpMessagePrimary` prop.

2024-02-29 19:42 UTC, sebastien-comeau commented on frontend/app/routes/_public+/intake+/$id+/dental-insurance.tsx
> +          <ButtonLink id="cancel-button" variant="alternative" to="/personal-information" className="w-24 border-blue-800 py-2 text-blue-800">
There's no need to match the mockup buttons at the moment. We can revisit our current button style later on. For now, let's stick with the default variant. If you need a larger button, you can adjust the size using the `size` prop. This also applies to the next button.

2024-02-29 20:03 UTC, nicholas-ly commented on frontend/app/routes/_public+/intake+/$id+/dental-insurance.tsx
> +                </Details>
Placing a `<details>` element as a direct child of an `<ul>` fails HTML validation. Consider placing the `<details>` within the corresponding `<li>` instead.

2024-02-29 20:22 UTC, nicholas-ly submitted a review, later dismissed

2024-02-29 21:52 UTC, sebastien-comeau requested changes
Final minor tweak.

2024-02-29 21:52 UTC, sebastien-comeau commented on frontend/app/routes/_public+/intake+/$id+/dental-insurance.tsx
> +              helpMessagePrimaryClassName="pl-8 text-[#333333]"
Default body color is black.

```suggestion
              helpMessagePrimaryClassName="pl-8 text-black"
```

2024-02-29 23:58 UTC, sebastien-comeau submitted a review, later dismissed

2024-03-01 00:10 UTC, sebastien-comeau approved these changes

2024-03-01 00:15 UTC, merged