AB#3197 - support no letter page
DTS-STN/canadian-dental-care-plan pull request #873
Opened 2024-04-02 19:35 UTC by leiye29

### Description
Display "There is no letter on file" when there is no letter found for login sin.

### Screenshots (if applicable)

![image](https://github.com/DTS-STN/canadian-dental-care-plan/assets/132592996/50ed4330-e3b9-4aa0-a392-8645eeee4954)

### Checklist

- [ ] I have tested the changes locally
- [ ] I have updated the documentation if necessary
- [ ] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

2024-04-02 20:32 UTC, nicholas-ly commented on frontend/public/locales/fr/letters.json
> +    "no-letter": "Il ñ'y a aucune lettre au dossier.",
```suggestion
    "no-letter": "Il n'y a aucune lettre au dossier.",
```

2024-04-02 21:37 UTC, leiye29 commented on frontend/public/locales/fr/letters.json
> +    "no-letter": "Il ñ'y a aucune lettre au dossier.",
fixed

2024-04-03 00:33 UTC, sebastien-comeau requested changes
Use return early pattern when `letters.length === 0`.

```tsx
if({letters.length === 0) {
  return <p>{t('letters:index.no-letter')}</p>
}

return (<>{ // sorting and listing as usual }</>;
```

2024-04-03 12:41 UTC, sebastien-comeau approved these changes

2024-04-03 12:41 UTC, merged